Instidropbox/Instidropbox/urls.py
"""
Definition of urls for Instidropbox.
"""

from datetime import datetime
from django.conf.urls import url
from django.conf.urls.static import static
import django.contrib.auth.views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^sign_up$', app.views.sign_up, name='sign_up'),

    url(r'^mydashboard$', app.views.mydashboard, name='mydashboard'),
    url(r'^studentgrievances$', app.views.studentgrievances, name='studentgrievances'),
    url(r'^sendgrievance$', app.views.sendgrievance, name='sendgrievance'),
    url(r'^sendgrievance/(?P<id>\d+)$', app.views.viewfaculty, name='viewfaculty'),

    #need to write faculty panel urls here
    url(r'^f_viewgrievances$', app.views.f_viewgrievances, name='f_viewgrievances'),
    url(r'^deptgrievances$', app.views.deptgrievances, name='deptgrievances'),
    url(r'^editstudentreq/(?P<id>\d+)$', app.views.editstudentreq, name='editstudentreq'),
    url(r'^f_updatereq/(?P<id>\d+)$', app.views.updatereq, name='f_updatereq'),
    url(r'^delete/(?P<id>\d+)$', app.views.destroy),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^sign_up$', app.views.sign_up, name='sign_up'),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


Instidropbox/app/models.py
"""
Definition of models.
"""
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_student=models.BooleanField(default=False, blank=True)
    is_faculty=models.BooleanField(default=False, blank=True)
    is_hod=models.BooleanField(default=False, blank=True)
    is_principal=models.BooleanField(default=False, blank=True)
    is_staff=models.BooleanField(default=False, blank=True)
    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Faculty(models.Model):
    Faculty_Id=models.CharField(max_length=10)
    Faculty_Name=models.CharField(max_length=50)
    DEPTS = [
    ('CSE', 'CSE'),
    ('MECH', 'MECH'),
    ('Civil', 'Civil'),
    ('ENC', 'ENC'),
    ('ISE', 'ISE'),
    ]
    Department=models.CharField(max_length=10,choices=DEPTS,default="CSE")
    DESIGNATIONS = [
    ('Principal', 'Principal'),
    ('Prof.', 'Professor'),
    ('HOD', 'HOD'),
    ('Asst.Prof.', 'Asst.Professor'),
    ('Asst.Prof.', 'Asso.Professor')
    ]
    Designation=models.CharField(max_length=20,choices=DESIGNATIONS,blank=True)
    Experience=models.IntegerField(help_text="Number of years",blank=True)
    Achievements=models.CharField(max_length=250,blank=True)
    Message=models.CharField(help_text="Message to students",max_length=250,blank=True)
    Contact=models.CharField(max_length=10,blank=True)
    Email=models.EmailField(max_length=50,blank=True)
    Photo=models.ImageField(upload_to='images/',blank=True)
    Place=models.TextField(max_length=100,blank=True)
    Created_Date=models.DateField(default=date.today,blank=True)

    def __str__(self):
        return self.Faculty_Name

class Faculty_subjects(models.Model):
   Faculty_Id=models.ForeignKey(Faculty)
   Subject=models.CharField(max_length=50,blank=True)
   Specialization=models.CharField(max_length=200,blank=True)
   Sub_notes=models.FileField(upload_to='documents/',blank=True)
   sub_Video=models.FileField(upload_to='videos/',blank=True)

   def __str__(self):
       return str(self.Subject)
   
class Students(models.Model):
    Student_Id=models.CharField(max_length=12)
    Student_Name=models.CharField(max_length=50)
    DEPTS = [
    ('CSE', 'CSE'),
    ('MECH', 'MECH'),
    ('Civil', 'Civil'),
    ('ENC', 'ENC'),
    ('ISE', 'ISE'),
    ]
    Department=models.CharField(max_length=10,choices=DEPTS,blank=True)
    Semester=models.PositiveIntegerField(blank=True)
    STATUSES=[
        ('Active','Active'),
        ('In Active','In Active'),
        ]
    Status=models.CharField(max_length=10,choices=STATUSES,blank=True,default="Active")
    Contact=models.CharField(max_length=10,blank=True)
    Email=models.EmailField(max_length=30,blank=True)
    def __str__(self):
        return str(self.Student_Name)+"_"+str(self.Student_Id)

class ReqTypes(models.Model):
    Req_Type_id=models.CharField(primary_key=True,max_length=25)
    Req_Type=models.CharField(max_length=25)
    
    def __str__(self):
        return self.Req_Type

class ReqDetails(models.Model):
    Req_Type=models.CharField(max_length=25)
    Req_details=models.CharField(max_length=250,blank=True)
    sender_id=models.CharField(max_length=10,blank=True)
    receiver_id=models.CharField(max_length=10,blank=True)
    Req_Status=models.CharField(max_length=20,default="Pending",blank=True)
    dateof_request=models.DateField(default=date.today,blank=True)
    dateof_update=models.DateField(default=date.today,blank=True)
    reply_details=models.CharField(max_length=250,blank=True)
    visibilty_sender_id=models.BooleanField(default=True,blank=True)
    document=models.FileField(upload_to='documents/',blank=True)
    visible_to_Hod=models.BooleanField(default=False,blank=True)
    visible_to_Principal=models.BooleanField(default=False,blank=True)
    def __str__(self):
        return str(self.Req_Type+"_")+str(self.sender_id)+"_to_"+str(self.receiver_id)













Instidropbox/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<!-- ======= Hero Section ======= -->
  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>About</h2>
          <p>About Application Design</p>
        </div>

        <div class="row">
          <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
            <img src="{% static "/assets/img/about.jpg" %}" class="img-fluid" alt="" width="500" height="400"/>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
            <h3>This application has been designed by using Django Framework version 1.11</h3>
            <p class="font-italic">
               Django gives you a powerful, patterns-based way to build dynamic websites that
               enables a clean separation of concerns and gives you full control over markup
               for enjoyable, agile development.
            </p>
            <ul>
              <li><i class="icofont-check-circled"></i> Django fallows MTV ( Model Template View ) Model </li>
              <li><i class="icofont-check-circled"></i>Language Used:Python 3.6 Object Oriented Programming Language </li>
              <li><i class="icofont-check-circled"></i>Backend Data Base: Sqlite3 </li>
              <li><i class="icofont-check-circled"></i>Tool Used: Visual Studio 2017 </li>
            </ul>
            <p>
              <a class="learn-more-btn" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a>
            </p>
               {#<a href="{% url 'login' %}" class="learn-more-btn">Login</a>#}
          </div>
        </div>

      </div>
    </section><!-- End About Section -->


 

    <!-- ======= Features Section ======= -->
    <!-- End Features Section -->

    

 
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  

  <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
  <div id="preloader"></div>

 
{% endblock %}
{% block scripts %}
 <!-- Vendor JS Files -->
  <script src="{% static "assets/vendor/jquery/jquery.min.js" %}" ></script>
  <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}" ></script>
  <script src="{% static "assets/vendor/jquery.easing/jquery.easing.min.js" %}" ></script>
  <script src="{% static "assets/vendor/php-email-form/validate.js" %}" ></script>
  <script src="{% static "assets/vendor/waypoints/jquery.waypoints.min.js" %}" ></script>
  <script src="{% static "assets/vendor/counterup/counterup.min.js" %}" ></script>
  <script src="{% static "assets/vendor/owl.carousel/owl.carousel.min.js" %}" ></script>
  <script src="{% static "assets/vendor/aos/aos.js" %}" ></script>

  <!-- Template Main JS File -->
  <script src="{% static "assets/js/main.js" %}" ></script>
{% endblock%}

Instidropbox/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<!-- ======= Hero Section ======= -->
   <main id="main">

    <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Contact Us</h2>
          <p>Designed and Developed By </p>
        </div>

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="{% static "assets/img/trainers/trainer-1.jpg" %}" class="img-fluid" alt="">
              <div class="member-content">
                <h4>Dhanushree D</h4>
                <span>2GP15CS006</span>
                <p>
                  Government Engineering College Majali, Karwar, Karnataka
                </p>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="{% static "assets/img/trainers/trainer-2.jpg" %}"  class="img-fluid" alt="">
              <div class="member-content">
                <h4>Gagan K S</h4>
                <span>2GP16CS004</span>
                <p>
                  Government Engineering College Majali, Karwar, Karnataka
                </p>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>
          
          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="{% static "assets/img/trainers/trainer-3.jpg" %}"  class="img-fluid" alt="">
              <div class="member-content">
                <h4>Saraswathi G</h4>
                <span>2GP16CS021</span>
                <p>
                  Government Engineering College Majali, Karwar, Karnataka
                </p>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
            <div class="member">
              <img src="{% static "assets/img/trainers/trainer-4.jpg" %}"  class="img-fluid" alt="">
              <div class="member-content">
                <h4>SharathKumar B P</h4>
                <span>2GP17CS408</span>
                <p>
                  Government Engineering College Majali, Karwar, Karnataka
                </p>
                <div class="social">
                  <a href=""><i class="icofont-twitter"></i></a>
                  <a href=""><i class="icofont-facebook"></i></a>
                  <a href=""><i class="icofont-instagram"></i></a>
                  <a href=""><i class="icofont-linkedin"></i></a>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  

  <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
  <div id="preloader"></div>

 
{% endblock %}
{% block scripts %}
 <!-- Vendor JS Files -->
  <script src="{% static "assets/vendor/jquery/jquery.min.js" %}" ></script>
  <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}" ></script>
  <script src="{% static "assets/vendor/jquery.easing/jquery.easing.min.js" %}" ></script>
  <script src="{% static "assets/vendor/php-email-form/validate.js" %}" ></script>
  <script src="{% static "assets/vendor/waypoints/jquery.waypoints.min.js" %}" ></script>
  <script src="{% static "assets/vendor/counterup/counterup.min.js" %}" ></script>
  <script src="{% static "assets/vendor/owl.carousel/owl.carousel.min.js" %}" ></script>
  <script src="{% static "assets/vendor/aos/aos.js" %}" ></script>

  <!-- Template Main JS File -->
  <script src="{% static "assets/js/main.js" %}" ></script>
{% endblock%}


Instidropbox/app/templates/app/deptgrievances.html
{% extends "app/facultylayout.html" %}

{% block content %}

    <div style="width:100%">
        <section id="viewgrievances">
            <form  method="post" class="form-horizontal">
             {% csrf_token %}
             <div class="form-group">
                 <input type="search" id="searchreq"  name="searchreq"  class="form-control" onkeyup="serchforReq()" placeholder="Search for req"/>
             {#<a class="btn btn-primary" href="{% url 'view_services' %}">Search &raquo;</a>#}
             <hr/>   
             <table class="table table-striped table-bordered" id="grievstable">
             <tr><th>Request type</th><th>Req details</th><th>Student</th><th>Reply Details</th><th>Document</th><th>Req Status</th><th>Date_of_Req</th><th>View Details</th></tr>             
            {% for gv in grews %}
             <tr> 
              <td>{{ gv.Req_Type }}</td>
              <td>{{ gv.Req_details }}</td>
              <td>{% if gv.visibilty_sender_id %}                 
                          <a href="#" class="control-label"> {{ gv.sender_id }}{#/f_viewgrievances/{{ f.id }}#}</a>
                  {% endif %}
                 </td>
              
              <td>{{ gv.reply_details }}</td>
              <td>{% if gv.document %} <a href="{{ gv.document }}" class="btn btn-warning btn-sm" download><span class="glyphicon glyphicon-save"></span> Reference</a>
                 {% endif %}
                 </td>
              <td>{{ gv.Req_Status }}</td>
              <td> {{ gv.dateof_request }}</td>
              <td> <a href="/f_updatereq/{{ gv.id }}" class="btn btn-info" role="button">View</a></td>
              </tr>
             {% endfor %}
             </table>
            </div>
            </form>
        </section>
    </div>
  
  <!-- Modal -->
  <div class="modal fade" id="detailsView" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Request Details</h4>
        </div>
        <div class="modal-body" id="dtls" onload="showdtls(this)">
          <p>Details need to display request details here using java script or use only alert to display details</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
  paginator({
  table: document.getElementById("grievstable").getElementsByTagName("table")[0],
  box: document.getElementById("box"),
});
</script>

{% endblock %}

Instidropbox/app/templates/app/editstudentreq.html
{% extends "app/studentlayout.html" %}

{% block content %}
<div>
    <form class="form-horizontal" method="post"> 
    {% csrf_token %}
    <div class="col-lg-8 col-sm-2">
      <h3>Request Form</h3> 
       {% if Success %}
        <div class="btn btn-sm btn-success"><p style="align-content:center"> Updated Successfully </p></div>
        {% endif %}
         <div class="form-group">
          <label for="req_type" class="col-md-4 control-label">Request Type</label>
          <div class="col-md-6">           
            <input type="text" class="form-control" name="req_type" value="{{ req.Req_Type }}" >
          </div>
        </div>
         <div class="form-group">
          <label for="req_details" class="col-md-4 control-label">Request Details</label>
          <div class="col-md-8"> 
             <textarea  class="form-control" name="req_details" rows="10" cols="37" maxlength="250">{{ req.Req_details }}</textarea>
          </div>
        </div>
         
         <div class="form-group">
          <label for="receiver" class="col-md-4 control-label">Faculty</label>
          <div class="col-md-6">
           <input type="text" name="receiver_id" class="form-control" value="{{ req.receiver_id }}"  maxlength="10" id="id_receiver_id"/>
          </div>
        </div>
         
         <div class="row">          
         <div class="form-group">
          <label for="visibilty_sender_id" class="col-md-4 control-label">Visibile:</label>
          <div class="col-sm-4">
              <input type="checkbox" name="visible_sender_id"/>
          </div>
        </div>
       <div class="form-group">
          <label for="visible_to_Hod" class="col-md-4 control-label">Visible To HOD:</label>
          <div class="col-sm-4">
            <input type="checkbox" name="visible_to_Hod"/>
          </div>
        </div>
        <div class="form-group">
          <label for="visible_to_Principal" class="col-md-4 control-label">Visibile to principal:</label>
          <div class="col-sm-4">
            <input type="checkbox" name="visible_to_Principal"/>
          </div>
        </div>
        </div>
        <div class="col-md-8 col-md-offset-4">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
                
   </div>
       
    <div class="col-md-4">
       <div class="panel panel-default form-group">
         <div class="panel-heading btn-primary"><strong>Faculties:</strong> 
           <select id="f_faculty" class="btn btn-primary">
               <option value="CSE">CSE
               </option>
               <option value="ENC">ENC
               </option>
               <option value="MECH">MECH
               </option>
               <option value="Civil">Civil
               </option>
               <option value="ENE">ENE
               </option>
           </select>
           </div>
         <div class="panel-body">
        {% for f in faculty  %}
        <ul class="list-group">
            <li class="list-group-item">
               <input type="radio" name="staff" value="{{ f.Faculty_Id }}" onclick="if (this.checked) { bind(this.value)}"><a href="/sendgrievance/{{ f.id }}" class="control-label">{{ f.Faculty_Name }}-{{ f.Faculty_Id }}</a>
            </li>
        </ul> 
        {% endfor %}
             </div>
           </div>

    </div>
                <!-- /.row this actually does not appear to be needed with the form-horizontal -->
  </form> 
</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
           <p>Need to display faculty details</p>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
<script>
    function bind(id) {
        document.getElementById("id_receiver_id").value = id;
    }
</script>

{% endblock %}

Instidropbox/app/templates/app/f_viewgrievances.html
{% extends "app/facultylayout.html" %}

{% block content %}

   
    <div style="width:100%">
        <section id="viewgrievances">
            <form  method="post" class="form-horizontal">
             {% csrf_token %}
             <div class="form-group">
                 <input type="search" id="searchreq"  name="searchreq"  class="form-control" onkeyup="serchforReq()" placeholder="Search for req"/>
             {#<a class="btn btn-primary" href="{% url 'view_services' %}">Search &raquo;</a>#}
             <hr/>   
             <table class="table table-striped table-bordered table-sm" id="grievstable">
             <tr><th>Request type</th><th>Req details</th><th>Student</th><th>Reply Details</th><th>Document</th><th>Req Status</th><th>Date_of_Req</th><th>View Details</th></tr>             
            {% for gv in grews %}
             <tr> 
              <td>{{ gv.Req_Type }}</td>
              <td>{{ gv.Req_details }}</td>
              <td>{% if gv.visibilty_sender_id %}                 
                          <a href="#" class="control-label"> {{ gv.sender_id }}{#/f_viewgrievances/{{ f.id }}#}</a>
                  {% endif %}
                 </td>
              
              <td>{{ gv.reply_details }}</td>
              <td>{% if gv.document %} <a href="{{ gv.document }}" class="btn btn-warning" download> <span class="glyphicon glyphicon-save"></span>Reference</a>
                 {% endif %}
                 </td>
              <td>{{ gv.Req_Status }}</td>
              <td> {{ gv.dateof_request }}</td>
              <td> <a href="/f_updatereq/{{ gv.id }}" class="btn btn-info" role="button">View</a></td>
              </tr>
             {% endfor %}
             </table>
            </div>
            </form>
        </section>
    </div>
  
  <!-- Modal -->
  <div class="modal fade" id="detailsView" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Request Details</h4>
        </div>
        <div class="modal-body" id="dtls" onload="showdtls(this)">
          <p>Details need to display request details here using java script or use only alert to display details</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>



{% endblock %}

Instidropbox/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
    <li><a href="{% url 'sign_up' %}">Sign Up</a></li>
</ul>

{% endif %}

Instidropbox/app/templates/app/sendgrievance.html
{% extends "app/studentlayout.html" %}

{% block content %}
<div>
    <form class="form-horizontal" method="post"> 
    {% csrf_token %}
    <div class="col-lg-8 col-sm-2">
      <h3>Request Form</h3> 
       
         <div class="form-group">
          <label for="req_type" class="col-md-4 control-label">Request Type</label>
          <div class="col-md-6">
            {{ form.Req_Type }}
            {#<input type="text" class="form-control" id="u_name" value="{{ std.Student_Id }}" disabled>#}
          </div>
        </div>
         <div class="form-group">
          <label for="req_details" class="col-md-4 control-label">Request Details</label>
          <div class="col-md-8">
            {{ form.Req_details }}
            {#<input type="text" class="form-control" id="u_name" value="{{ std.Student_Id }}" disabled>#}
          </div>
        </div>
         <div class="form-group">
          <label for="sender_id" class="col-md-4 control-label">Sender ID</label>
          <div class="col-md-6">
            {#{{ form.sender_id }}#}
               <input type="text" name="sender_id" class="form-control" value="{{ user.username }}" placeholder="Sender id" maxlength="10" id="id_sender_id" />
           
          </div>
        </div>
         <div class="form-group">
          <label for="receiver" class="col-md-4 control-label">Faculty</label>
          <div class="col-md-6">
            {{ form.receiver_id }}
              {#<input type="text" name="receiver_id" class="form-control"  placeholder="Faculty name" maxlength="10" id="id_receiver_id" disabled/>#}
           
          </div>
        </div>
         <div class="form-group">
          <label for="req_status" class="col-md-4 control-label">Request Status:</label>
          <div class="col-md-6">
            {{ form.Req_Status }}
          
          </div>
        </div>
         <div class="form-group">
          <label for="dateof_request" class="col-md-4 control-label">Date:</label>
          <div class="col-md-6">
            {{ form.dateof_request }}
            
          </div>
        </div>
        <div class="row">
          
         <div class="form-group">
          <label for="visibilty_sender_id" class="col-md-4 control-label">Visible:</label>
          <div class="col-md-6">
            {{ form.visibilty_sender_id }}
            
          </div>
        </div>
        <div class="form-group">
          <label for="visible_to_Hod" class="col-md-4 control-label">Visible To HOD:</label>
          <div class="col-md-6">
            {{ form.visible_to_Hod }}
          
          </div>
        </div>
        <div class="form-group">
          <label for="visible_to_Principal" class="col-md-4 control-label">Visibile to principal:</label>
          <div class="col-md-6">
            {{ form.visible_to_Principal }}
           
          </div>
        </div>
        </div>
        <div class="col-md-8 col-md-offset-4">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
                
   </div>
       
    <div class="col-md-4">
       <div class="panel panel-default form-group">
         <div class="panel-heading btn-primary"><strong>Faculties:-</strong> 
           <!--<select id="f_faculty" class="btn btn-primary" hidden>
               <option value="CSE">CSE
               </option>
               <option value="ECE">ENC
               </option>
               <option value="Mechanical">MECH
               </option>
           </select>-->
           </div>
         <div class="panel-body">
        {% for f in faculty  %}
        <ul class="list-group">
            <li class="list-group-item">
               <input type="radio" name="staff" value="{{ f.Faculty_Id }}" onclick="if (this.checked) { bind(this.value)}"><a href="/sendgrievance/{{ f.id }}" class="control-label">{{ f.Faculty_Name }}-{{ f.Faculty_Id }}</a>
            </li>
        </ul>
                   
        {% endfor %}
             </div>
           </div>

    </div>
                <!-- /.row this actually does not appear to be needed with the form-horizontal -->
  </form> 
</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
           <p>Need to display faculty details</p>
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
<script>
    function bind(id) {
        document.getElementById("id_receiver_id").value = id;
    }
</script>

{% endblock %}